name: Update readme

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install -y ffmpeg
          python -m pip install --upgrade pip
          pip install github-readme-terminal

      - name: Run script
        run: python main.py
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          IMGBB_API_KEY: ${{ secrets.IMGBB_API_KEY }}
          GIFOS_GENERAL_COLOR_SCHEME: "catppuccin-mocha"
          GIFOS_GENERAL_USER_NAME: "mementomorri"

      - name: Update readme
        run: |
          git add README.md
          git -c "user.name=bot" -c "user.email=bot@github.com" commit -m "Automatically updated on $(TZ='Europe/Moscow' date)"
          git push --force
